test name 1:
  httpUrl: https://www.google.com
  expectedStatusCodes: ["200"]

test name 2:
  httpUrl: https://google.com
  expectedStatusCodes: ["301", "200"]

test name 3:
  httpUrl: https://google.com/lol/wtf
  httpHeaders: ["X-file=awesome.png"]
  expectedStatusCodes: ["404"]
