# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Requester < Formula
  desc "A simple tool (<200 lines of code) to test concurrently HTTP requests status codes following its redirects."
  homepage "https://github.com/Alana-Research/requester"
  version "0.0.2"
  license "MIT license"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Alana-Research/requester/releases/download/v0.0.2/requester_0.0.2_Darwin_arm64.tar.gz"
      sha256 "60bfe87253b2cdcf3995fbc131687f06954e8562e2c424c0e09f38b2eee04a92"

      def install
        bin.install "requester"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Alana-Research/requester/releases/download/v0.0.2/requester_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "f5410fd4f71b00ecbdff7a528e2b9392f24ed622f50c49ac8c0dd46cb7820431"

      def install
        bin.install "requester"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Alana-Research/requester/releases/download/v0.0.2/requester_0.0.2_Linux_x86_64.tar.gz"
      sha256 "5a78bbe018c87b034abd0265cb6669bc978c41a59a061a58c40dcafe1beca998"

      def install
        bin.install "requester"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Alana-Research/requester/releases/download/v0.0.2/requester_0.0.2_Linux_armv6.tar.gz"
      sha256 "bed6036866094a8191388922e33b721f2b7e216d57bdabfcc11c7f81e1c40679"

      def install
        bin.install "requester"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Alana-Research/requester/releases/download/v0.0.2/requester_0.0.2_Linux_arm64.tar.gz"
      sha256 "0416d95195799dd5ca4e031198c6748410e67221f6040caf0f4117bc600dacda"

      def install
        bin.install "requester"
      end
    end
  end
end
