# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Requester < Formula
  desc "A simple tool (<200 lines of code) to test concurrently HTTP requests status codes following its redirects."
  homepage "https://github.com/Alana-Research/requester"
  version "0.0.1-test"
  license "MIT license"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Alana-Research/requester/releases/download/v0.0.1-test/requester_0.0.1-test_Darwin_x86_64.tar.gz"
      sha256 "c0b6cd9e1b6e582a1e33f01f2c9f29cc2ea9be97ef85023f406dc8fd4a2d0919"

      def install
        bin.install "requester"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Alana-Research/requester/releases/download/v0.0.1-test/requester_0.0.1-test_Darwin_arm64.tar.gz"
      sha256 "476247d9b76533cd2839c4f54126bc8446240e6f5ccb4cca6f0af96d794843ef"

      def install
        bin.install "requester"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Alana-Research/requester/releases/download/v0.0.1-test/requester_0.0.1-test_Linux_armv6.tar.gz"
      sha256 "9f467b10f35143eae79867ea79ee640b9393e6f3590e08c7f1b452be1abe8eb6"

      def install
        bin.install "requester"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Alana-Research/requester/releases/download/v0.0.1-test/requester_0.0.1-test_Linux_x86_64.tar.gz"
      sha256 "2661b54a21aa9a92e8fe72bd676b3730afa9e7315e437fdb2ac6df0df38e9685"

      def install
        bin.install "requester"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Alana-Research/requester/releases/download/v0.0.1-test/requester_0.0.1-test_Linux_arm64.tar.gz"
      sha256 "c54d2927ac29eaa696e4e6d2208247af5a08c0aed91aa097558205f3adb78fd3"

      def install
        bin.install "requester"
      end
    end
  end
end
