# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Requester < Formula
  desc "A simple tool (<200 lines of code) to test concurrently HTTP requests status codes following its redirects."
  homepage "https://github.com/Alana-Research/requester"
  version "0.0.3"
  license "MIT license"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Alana-Research/requester/releases/download/v0.0.3/requester_0.0.3_Darwin_x86_64.tar.gz"
      sha256 "296d336843a9059c37f48b10947875280dc546fb1f8d327b7b8901fb85c99f34"

      def install
        bin.install "requester"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Alana-Research/requester/releases/download/v0.0.3/requester_0.0.3_Darwin_arm64.tar.gz"
      sha256 "cd17ceb4d6902ff6474b703acb4f584110244bf443d28e737a6db3d0fe7ffc71"

      def install
        bin.install "requester"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Alana-Research/requester/releases/download/v0.0.3/requester_0.0.3_Linux_armv6.tar.gz"
      sha256 "1570095ea943db4977d22261e424a6750f4649ea451f091c0105aa0607e054f3"

      def install
        bin.install "requester"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Alana-Research/requester/releases/download/v0.0.3/requester_0.0.3_Linux_x86_64.tar.gz"
      sha256 "6b4d1bd7ce883c0cbebcdae3cc3aeffc4e80d6088b40b53f085355a93c12051a"

      def install
        bin.install "requester"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Alana-Research/requester/releases/download/v0.0.3/requester_0.0.3_Linux_arm64.tar.gz"
      sha256 "1571b2b71551ab47d7e781953f4f7a20a94e09b399f7f33adb24150b15fb7f44"

      def install
        bin.install "requester"
      end
    end
  end
end
